### ISSUE TITLE
Seems to get stuck when stirring the stick into the H2O2

### ISSUE THREAD

**Issue by artlogic** [arsmentis/vibl#9]
Catalase: Seems to get stuck when stirring the stick into the H2O2. I tried with both S. pyogenes (should be negative) and S. aureus (should be positive but no bubbles were observed).

Coagulase: same issue with getting stuck at step where stick with bacteria is mixing in solution (water) on the slide. Can’t progress pass the step to see if there are any other problems.

Logged in a single issue because they appear to be the same problem.

**Comment by artlogic** [comment]
Caching related?

**Comment by x246** [comment]
I had modified ToolPresentationEngine.js, which is used in most modules. I think this wasn't updated when the client tested. Let me know if they still have the problem. Thanks!

**Comment by artlogic** [comment]
Fixed
